### PR TITLE
Fix for GCC 6 compilation

### LINKED ISSUE #17: Strange compile error
Hello,

I was previously able to compile PMGD on my Ubuntu 16.04 system. 

Recently, I upgraded to Ubuntu 18.04 and tried to do a fresh compile of PMGD but am now getting some strange errors:

---------------------------------------------
~/VARS/pmgd/test$ make all
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[CC] src/graph.o
[CC] src/GraphConfig.o
[CC] src/node.o
[CC] src/edge.o
[CC] src/StringTable.o
[CC] src/PropertyList.o
[CC] src/property.o
[CC] src/stringid.o
In file included from src/property.cc:31:0:
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::PropertyList’
         uint8_t _chunk0[];
                         ^
In file included from ./include/edge.h:34:0,
                 from src/edge.cc:31:
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::PropertyList’
         uint8_t _chunk0[];
                         ^
src/Makeconf:35: recipe for target 'src/property.o' failed
make[1]: *** [src/property.o] Error 1
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::Edge’
[CC] src/TransactionManager.o
In file included from ./include/graph.h:34:0,
                 from ./include/transaction.h:33,
                 from src/TransactionImpl.h:38,
                 from src/StringTable.cc:33:
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::PropertyList’
         uint8_t _chunk0[];
                         ^
In file included from ./include/graph.h:34:0,
                 from src/GraphConfig.cc:33:
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::PropertyList’
         uint8_t _chunk0[];
                         ^
In file included from ./include/graph.h:34:0,
                 from src/graph.cc:32:
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::PropertyList’
         uint8_t _chunk0[];
                         ^
In file included from src/node.cc:33:0:
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::PropertyList’
         uint8_t _chunk0[];
                         ^
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::Node’
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::Edge’
In file included from ./include/graph.h:34:0,
                 from src/PropertyList.cc:36:
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::PropertyList’
         uint8_t _chunk0[];
                         ^
In file included from ./include/graph.h:34:0,
                 from ./include/transaction.h:33,
                 from src/TransactionImpl.h:38,
                 from src/stringid.cc:34:
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::PropertyList’
         uint8_t _chunk0[];
                         ^
src/Makeconf:35: recipe for target 'src/StringTable.o' failed
make[1]: *** [src/StringTable.o] Error 1
[CC] src/transaction.o
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::Node’
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::Node’
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::Edge’
In file included from ./include/graph.h:34:0,
                 from ./include/transaction.h:33,
                 from src/TransactionImpl.h:38,
                 from src/TransactionManager.cc:33:
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::PropertyList’
         uint8_t _chunk0[];
                         ^
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::Node’
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::Edge’
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::Node’
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::Edge’
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::Node’
./include/iterator.h:259:25: error: flexible array member ‘PMGD::PropertyList::_chunk0’ in an otherwise empty ‘class PMGD::Edge’
src/Makeconf:35: recipe for target 'src/edge.o' failed
make[1]: *** [src/edge.o] Error 1
[CC] src/Index.o
src/Makeconf:35: recipe for target 'src/GraphConfig.o' failed
make[1]: *** [src/GraphConfig.o] Error 1
----------------------------------------
There are, of course, many more errors showing up now.

Did I miss something here?
Cheer

### PR DESCRIPTION
**Pull request by luisremis**
Fixes #17

### CODE REVIEW

**Comment by vishakha041** [comment]
This is not the only fix needed for gcc version changes. I have more in my branch. Will push a bug fix branch later today.

**Comment by luisremis** [comment]
great, thanks!

**Comment by lonnieOST** [comment]
great, to hear and I will try the new "push" after it comes out.

Will these fixes also be on the ConcurrencywithMSync" branch as well?

Cheers :)

**Comment by luisremis** [comment]
Yes, all those changes and the concurrency branch will be merged into the main branch soon.

**Comment by luisremis** [comment]
I remember you mentioned this, but in your PR, that is the only change that it seems it there for gcc 6.
I am missing something, or maybe you forgot to include them and it is sitting there in a local branch.

-Luis

On Oct 22, 2018, at 11:53 AM, Vishakha Gupta-Cledat <notifications@github.com<mailto:notifications@github.com>> wrote:


This is not the only fix needed for gcc version changes. I have more in my branch. Will push a bug fix branch later today.

**Pull request closed without merging**
